isitechphp_main:
    resource: "@isitechphpMainBundle/Controller/"
    type:     annotation
    prefix:   /

isitechphp_user:
    resource: "@isitechphpUserBundle/Controller/"
    type:     annotation
    prefix:   /

isitechphp_admin:
    resource: "@isitechphpAdminBundle/Controller/"
    type:     annotation
    prefix:   /

sample_admin:
    resource: "@SampleAdminBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
